// <auto-generated />
using System;
using Infraestrutura.Vestibular.Contextos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestrutura.Vestibular.Migrations
{
    [DbContext(typeof(VestibularDB))]
    [Migration("20240811191933_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Modelo.Vestibular.Entidades.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdIncricao")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("Modelo.Vestibular.Entidades.Inscricao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCadidatos")
                        .HasColumnType("int");

                    b.Property<int>("IdOferta")
                        .HasColumnType("int");

                    b.Property<int>("IdProcessoSeletivo")
                        .HasColumnType("int");

                    b.Property<int>("NumInscricao")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdCadidatos");

                    b.HasIndex("IdOferta");

                    b.HasIndex("IdProcessoSeletivo");

                    b.HasIndex("NumInscricao")
                        .IsUnique();

                    b.ToTable("Inscricoes");
                });

            modelBuilder.Entity("Modelo.Vestibular.Entidades.Oferta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdIncricao")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumVagas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ofertas");
                });

            modelBuilder.Entity("Modelo.Vestibular.Entidades.ProcessoSeletivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataDeInicil")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeTermio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdIncricao")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProcessoSeletivos");
                });

            modelBuilder.Entity("Modelo.Vestibular.Entidades.Inscricao", b =>
                {
                    b.HasOne("Modelo.Vestibular.Entidades.Candidato", "Candidato")
                        .WithMany("Incricoes")
                        .HasForeignKey("IdCadidatos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelo.Vestibular.Entidades.Oferta", "Oferta")
                        .WithMany("Incricoes")
                        .HasForeignKey("IdOferta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelo.Vestibular.Entidades.ProcessoSeletivo", "ProcessoSeletivo")
                        .WithMany("Incricoes")
                        .HasForeignKey("IdProcessoSeletivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidato");

                    b.Navigation("Oferta");

                    b.Navigation("ProcessoSeletivo");
                });

            modelBuilder.Entity("Modelo.Vestibular.Entidades.Candidato", b =>
                {
                    b.Navigation("Incricoes");
                });

            modelBuilder.Entity("Modelo.Vestibular.Entidades.Oferta", b =>
                {
                    b.Navigation("Incricoes");
                });

            modelBuilder.Entity("Modelo.Vestibular.Entidades.ProcessoSeletivo", b =>
                {
                    b.Navigation("Incricoes");
                });
#pragma warning restore 612, 618
        }
    }
}
