CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Leads" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(150) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "Telefone" character varying(12) NOT NULL,
    "Cpf" text NOT NULL,
    CONSTRAINT "PK_Leads" PRIMARY KEY ("Id")
);

CREATE TABLE "Ofertas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(150) NOT NULL,
    "Descricao" character varying(250) NOT NULL,
    "VagasDisponiveis" integer NOT NULL,
    CONSTRAINT "PK_Ofertas" PRIMARY KEY ("Id")
);

CREATE TABLE "ProcessoSeletivos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(150) NOT NULL,
    "DataInicio" date NOT NULL,
    "DataFim" date NOT NULL,
    CONSTRAINT "PK_ProcessoSeletivos" PRIMARY KEY ("Id")
);

CREATE TABLE "Inscricoes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NumeroInscricao" character varying(8) NOT NULL,
    "Data" date NOT NULL,
    "Status" boolean NOT NULL,
    "LeadId" integer NOT NULL,
    "OfertaId" integer NOT NULL,
    "ProcessoSeletivoId" integer NOT NULL,
    CONSTRAINT "PK_Inscricoes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Inscricoes_Leads_LeadId" FOREIGN KEY ("LeadId") REFERENCES "Leads" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Inscricoes_Ofertas_OfertaId" FOREIGN KEY ("OfertaId") REFERENCES "Ofertas" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Inscricoes_ProcessoSeletivos_ProcessoSeletivoId" FOREIGN KEY ("ProcessoSeletivoId") REFERENCES "ProcessoSeletivos" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Inscricoes_LeadId" ON "Inscricoes" ("LeadId");

CREATE INDEX "IX_Inscricoes_OfertaId" ON "Inscricoes" ("OfertaId");

CREATE INDEX "IX_Inscricoes_ProcessoSeletivoId" ON "Inscricoes" ("ProcessoSeletivoId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240829063339_dados_iniciais', '6.0.0');

COMMIT;

